#!/bin/bash

run () {
  echo " * Running service"
  coffee ./app.coffee
}

run-dev () {
  echo " * Running service dev"
  nodemon ./app.coffee
}



case "$1" in

  run)
    run
    ;;

  run-dev)
    run-dev
    ;;

  bash)
    /bin/bash
    ;;
esac
